name: Deploy Lean 4 Game to GitHub Pages
on:
  push:
    branches: [main]
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ojwatson/setup-leantools@v2
        with:
          lean-version: latest
      - name: Build Lean game
        run: lake build
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install & build web
        working-directory: web
        run: |
          npm install
          npm run build
      - name: Deploy to Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          publish_dir: ./dist
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}